
# server.port
server:
  port: 9040
  
# mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springframework?serverTimezone=Asia/Seoul
    username: root
    password: dla570426
    
# JPA setting
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
# jsp setting
  mvc:
    view:
      prefix: /WEB-INF/movie/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true

